controller_joint_names: ['', 'rightjoint1', 'rightjoint2', 'rightjoint3', 'rightjoint4', 'rightjoint5', 'rightjoint6', 'leftjoint1', 'leftjoint2', 'leftjoint3', 'leftjoint4', 'leftjoint5', 'leftjoint6', ]
