_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
algorithm:
    value:
        clip_param: 0.2
        desired_kl: 0.01
        entropy_coef: 0.001
        gamma: 0.994
        lam: 0.9
        learning_rate: 1e-05
        max_grad_norm: 1
        num_learning_epochs: 2
        num_mini_batches: 4
        schedule: adaptive
        use_clipped_value_loss: true
        value_loss_coef: 1
asset:
    value:
        angular_damping: 0
        armature: 0
        collapse_fixed_joints: true
        default_dof_drive_mode: 3
        density: 0.001
        disable_gravity: false
        file: '{LEGGED_GYM_ROOT_DIR}/resources/robots/alexbotmini/urdf/alexbotmini.urdf'
        fix_base_link: false
        flip_visual_attachments: false
        foot_name: "6"
        knee_name: "4"
        linear_damping: 0
        max_angular_velocity: 1000
        max_linear_velocity: 1000
        name: alexbotmini
        penalize_contacts_on:
            - base_link
            - rightlink2
            - leftlink2
        replace_cylinder_with_capsule: false
        self_collisions: 1
        terminate_after_contacts_on:
            - base_link
            - rightlink2
            - leftlink2
        terminate_after_height_lower: []
        thickness: 0.01
commands:
    value:
        curriculum: false
        heading_command: true
        max_curriculum: 1
        num_commands: 4
        ranges:
            ang_vel_yaw:
                - -0.3
                - 0.3
            heading:
                - -3.14
                - 3.14
            lin_vel_x:
                - -0.3
                - 0.3
            lin_vel_y:
                - -0.3
                - 0.6
        resampling_time: 8
control:
    value:
        action_scale: 0.25
        damping:
            "1": 3
            "2": 2
            "3": 2
            "4": 3
            "5": 0.3
            "6": 0.3
        decimation: 10
        stiffness:
            "1": 120
            "2": 80
            "3": 80
            "4": 120
            "5": 15
            "6": 15
domain_rand:
    value:
        added_mass_range:
            - -2
            - 2
        dynamic_randomization: 0.02
        friction_range:
            - 0.1
            - 2
        max_push_ang_vel: 0.4
        max_push_vel_xy: 0.2
        push_interval: 400
        push_interval_s: 4
        push_robots: true
        randomize_base_mass: true
        randomize_friction: true
env:
    value:
        c_frame_stack: 3
        env_spacing: 3
        episode_length_s: 24
        frame_stack: 15
        num_actions: 12
        num_envs: 1000
        num_observations: 705
        num_privileged_obs: 219
        num_single_obs: 47
        send_timeouts: true
        single_num_privileged_obs: 73
        use_ref_actions: false
init_state:
    value:
        ang_vel:
            - 0
            - 0
            - 0
        default_joint_angles:
            leftjoint1: -0.2
            leftjoint2: 0
            leftjoint3: 0
            leftjoint4: 0.6
            leftjoint5: -0.4
            leftjoint6: 0
            rightjoint1: 0.2
            rightjoint2: 0
            rightjoint3: 0
            rightjoint4: -0.6
            rightjoint5: 0.4
            rightjoint6: 0
        lin_vel:
            - 0
            - 0
            - 0
        pos:
            - 0
            - 0
            - 0.7
        rot:
            - 0
            - 0
            - 0
            - 1
noise:
    value:
        add_noise: true
        noise_level: 0.6
        noise_scales:
            ang_vel: 0.1
            dof_pos: 0.05
            dof_vel: 0.5
            height_measurements: 0.1
            lin_vel: 0.05
            quat: 0.03
normalization:
    value:
        clip_actions: 18
        clip_observations: 18
        obs_scales:
            ang_vel: 1
            dof_pos: 1
            dof_vel: 0.05
            height_measurements: 5
            lin_vel: 2
            quat: 1
policy:
    value:
        actor_hidden_dims:
            - 512
            - 256
            - 128
        critic_hidden_dims:
            - 768
            - 256
            - 128
        init_noise_std: 1
rewards:
    value:
        base_height_target: 0.65
        cycle_time: 0.64
        max_contact_force: 200
        max_dist: 0.5
        min_dist: 0.2
        only_positive_rewards: false
        scales:
            action_smoothness: -0.002
            base_acc: 0.2
            base_height: 0.2
            collision: -1
            default_joint_pos: 0.35
            dof_acc: -1e-07
            dof_vel: -0.0005
            feet_air_time: 2.5
            feet_clearance: 2
            feet_contact_forces: -0.01
            feet_contact_number: 2.5
            feet_distance: 0.2
            foot_slip: -0.12
            joint_pos: 2
            knee_distance: 0.2
            low_speed: 0.2
            orientation: 1
            torques: -1e-05
            track_vel_hard: 0.5
            tracking_ang_vel: 1.1
            tracking_lin_vel: 1.4
            vel_mismatch_exp: 0.5
        target_feet_height: 0.04
        target_joint_pos_scale: 0.17
        tracking_sigma: 5
runner:
    value:
        algorithm_class_name: PPO
        checkpoint: -1
        experiment_name: alexbotmini
        load_run: -1
        max_iterations: 500
        num_steps_per_env: 60
        policy_class_name: ActorCritic
        resume: false
        resume_path: null
        run_name: ""
        save_interval: 100
runner_class_name:
    value: OnPolicyRunner
safety:
    value:
        pos_limit: 1
        torque_limit: 0.85
        vel_limit: 1
seed:
    value: 3407
sim:
    value:
        dt: 0.001
        gravity:
            - 0
            - 0
            - -9.81
        physx:
            bounce_threshold_velocity: 0.1
            contact_collection: 2
            contact_offset: 0.01
            default_buffer_size_multiplier: 5
            max_depenetration_velocity: 1
            max_gpu_contact_pairs: 8388608
            num_position_iterations: 4
            num_threads: 10
            num_velocity_iterations: 0
            rest_offset: 0
            solver_type: 1
        substeps: 1
        up_axis: 1
terrain:
    value:
        border_size: 25
        curriculum: false
        dynamic_friction: 0.6
        horizontal_scale: 0.1
        max_init_terrain_level: 10
        measure_heights: false
        measured_points_x:
            - -0.8
            - -0.7
            - -0.6
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
            - 0.6
            - 0.7
            - 0.8
        measured_points_y:
            - -0.5
            - -0.4
            - -0.3
            - -0.2
            - -0.1
            - 0
            - 0.1
            - 0.2
            - 0.3
            - 0.4
            - 0.5
        mesh_type: trimesh
        num_cols: 20
        num_rows: 20
        num_sub_terrains: 400
        restitution: 0
        selected: false
        slope_treshold: 0.75
        static_friction: 0.6
        terrain_kwargs: null
        terrain_length: 8
        terrain_proportions:
            - 0.2
            - 0.2
            - 0.4
            - 0.1
            - 0.1
            - 0
            - 0
        terrain_width: 8
        vertical_scale: 0.005
viewer:
    value:
        lookat:
            - 11
            - 5
            - 3
        pos:
            - 10
            - 0
            - 6
        ref_env: 0
